# Generated by Django 3.2.7 on 2021-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(choices=[('bahrain', 'Bahrain'), ('erbil', 'Erbil'), ('dubai', 'Dubai'), ('iraq', 'Iraq')], max_length=128, verbose_name='country'),
        ),
    ]
