# Generated by Django 3.2.7 on 2021-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_type', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_numer', models.CharField(blank=True, max_length=255, null=True)),
                ('cpr', models.CharField(max_length=255, unique=True)),
                ('talabat_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('designation_id', models.IntegerField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('visa', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_make_model', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('license_expiry_date', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('cpr_image', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_image', models.CharField(blank=True, max_length=255, null=True)),
                ('license_image', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_image', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_file', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('cnd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryStructures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hourly_rate', models.CharField(max_length=255)),
                ('per_drop', models.CharField(blank=True, max_length=256, null=True)),
                ('houry_rate_temp', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_rate', models.CharField(max_length=255)),
                ('extra_per_utr', models.CharField(blank=True, max_length=45, null=True)),
                ('per_km', models.CharField(blank=True, max_length=45, null=True)),
                ('long_distance_1', models.CharField(blank=True, max_length=45, null=True)),
                ('long_distance_2', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('overtime_rate', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'salary_structures',
                'managed': False,
            },
        ),
    ]
