# Generated by Django 3.2.7 on 2021-09-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employees_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="salary_structure",
            field=models.ForeignKey(
                db_column="salary_structure",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="employees.salarystructures",
            ),
        ),
    ]
