# Generated by Django 3.2.7 on 2021-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210909_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('TAM', 'TAM')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='country',
            field=models.CharField(blank=True, choices=[('Bahrain', 'Bahrain'), ('Erbil', 'Erbil'), ('Dubai', 'Dubai')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Motorbike', 'Motorbike'), ('Motor', 'Motor'), ('HATCHBACK', 'HATCHBACK')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='visa',
            field=models.CharField(blank=True, choices=[('Flexi Visa', 'Flexi Visa'), ('notflexi', 'Not Flexi'), ('KA Visa', 'KA Visa'), ('Free Visa', 'Free Visa')], max_length=255, null=True),
        ),
    ]
