# Generated by Django 3.2.7 on 2021-09-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210913_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department_id',
            field=models.ForeignKey(blank=True, db_column='department_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_employees', to='employees.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='designation_id',
            field=models.ForeignKey(blank=True, db_column='designation_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='designation_employees', to='employees.designations'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='team_id',
            field=models.ForeignKey(blank=True, db_column='team_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_employees', to='employees.teams'),
        ),
    ]
