# Generated by Django 3.2.7 on 2021-09-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210913_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performances',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('starting_date', models.CharField(max_length=255)),
                ('ending_date', models.CharField(max_length=255)),
                ('shift_count', models.CharField(max_length=255)),
                ('no_shows', models.CharField(max_length=255)),
                ('late_login', models.CharField(max_length=255)),
                ('completed_orders', models.CharField(max_length=255)),
                ('cancelled_orders', models.CharField(max_length=255)),
                ('cancellation_10_orders', models.CharField(max_length=255)),
                ('utr', models.CharField(max_length=255)),
                ('total_working_hours', models.CharField(max_length=255)),
                ('total_break_hours', models.CharField(max_length=255)),
                ('attendance_percentage', models.CharField(max_length=255)),
                ('breaks_percentage', models.CharField(max_length=255)),
                ('notification_count', models.CharField(max_length=255)),
                ('acceptance_count', models.CharField(max_length=255)),
                ('acceptance_rate', models.CharField(max_length=255)),
                ('avg_customer_time', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'performances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('hours', models.CharField(max_length=255)),
                ('orders', models.CharField(blank=True, max_length=255, null=True)),
                ('utr', models.CharField(blank=True, max_length=45, null=True)),
                ('po_orders', models.CharField(max_length=256)),
                ('po_hours', models.CharField(max_length=256)),
                ('day_deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_per_distance', models.CharField(blank=True, max_length=45, null=True)),
                ('extra_per_utr', models.CharField(blank=True, max_length=45, null=True)),
                ('day_deduction_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('double_orders', models.CharField(blank=True, max_length=255, null=True)),
                ('long_distance_sakhir', models.CharField(blank=True, max_length=45, null=True)),
                ('long_distance_durra', models.CharField(blank=True, max_length=45, null=True)),
                ('month', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
            ],
            options={
                'db_table': 'timesheets',
            },
        ),
    ]
