# Generated by Django 3.2.7 on 2021-09-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_performances_timesheets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performances',
            options={},
        ),
    ]
