# Generated by Django 3.2.7 on 2021-09-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_performances_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('pending_balance', models.CharField(max_length=255)),
                ('last_deposit_amount', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cnds',
                'managed': False,
            },
        ),
    ]
