# Generated by Django 3.2.7 on 2021-09-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_cnds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cnds',
            options={},
        ),
    ]
