# Generated by Django 3.2.7 on 2021-09-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_cnds_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnds',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees'),
        ),
    ]
