# Generated by Django 3.2.7 on 2021-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_cnds_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslips',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.CharField(blank=True, max_length=45, null=True)),
                ('bonus', models.CharField(blank=True, max_length=45, null=True)),
                ('deduction', models.CharField(blank=True, max_length=45, null=True)),
                ('net_payable', models.CharField(max_length=255)),
                ('salary_month', models.CharField(max_length=255)),
                ('payroll_entry_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payslips',
                'managed': False,
            },
        ),
    ]
