# Generated by Django 3.2.7 on 2021-09-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_payslips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslips',
            options={},
        ),
    ]
