# Generated by Django 3.2.7 on 2021-09-17 18:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_payslips_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashNds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_date', models.CharField(max_length=255)),
                ('previous_pending', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('previous_deposit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bonus_type', models.CharField(blank=True, max_length=255, null=True)),
                ('date_selected', models.CharField(max_length=255)),
                ('date_cod', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_pending', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deposit_status', models.CharField(max_length=255)),
                ('deposit_delayed', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cash_nds',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='employees',
            name='country',
            field=models.CharField(blank=True, choices=[('bahrain', 'Bahrain'), ('erbil', 'Erbil'), ('dubai', 'Dubai'), ('iraq', 'Iraq')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='cpr_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='license_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='passport_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('inactive', 'Inactive'), ('Salary Suspended', 'Salary Suspended'), ('Terminated', 'Terminated'), ('vacation', 'Vacation')], default='Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='verified',
            field=models.CharField(blank=True, choices=[('IBAN Verified', 'IBAN Verified'), ('no', 'No')], default='no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='visa_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
