# Generated by Django 3.2.7 on 2021-09-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20210917_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashnds',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees'),
        ),
    ]
