# Generated by Django 3.2.7 on 2021-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_cashnds_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=256, null=True)),
                ('balance', models.IntegerField()),
                ('holderid', models.IntegerField(db_column='holderID')),
                ('supplier_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('customer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accounttypename', models.CharField(db_column='accountTypeName', max_length=255)),
                ('subaccount', models.IntegerField(blank=True, db_column='subAccount', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_types',
                'managed': False,
            },
        ),
    ]
