# Generated by Django 3.2.7 on 2021-09-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_accountcategories_accounts_accounttypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accounts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accounttypes',
            options={},
        ),
    ]
