# Generated by Django 3.2.7 on 2021-09-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20210917_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('inactive', 'Inactive'), ('Salary Suspended', 'Salary Suspended'), ('Terminated', 'Terminated'), ('vacation', 'Vacation')], default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='verified',
            field=models.CharField(choices=[('IBAN Verified', 'IBAN Verified'), ('no', 'No')], default='No', max_length=255),
        ),
    ]
