# Generated by Django 3.2.7 on 2021-09-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_auto_20210917_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='cashnds',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='payslips',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='performances',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
    ]
